ENT.Base = "base_gmodentity"
ENT.Type = "anim"
ENT.PrintName = "Fingerprint Scanner"
ENT.Category = "Eggroll's Police System"
ENT.Author = "TheAsian EggrollMaker"
ENT.Contact = "theasianeggrollmaker@gmail.com"
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = true
