name: CI/CD

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and unpack glualint
        run: |
          wget https://github.com/FPtje/GLuaFixer/releases/download/1.18.1/glualint-1.18.1-linux-stripped.zip
          unzip glualint-1.18.1-linux-stripped.zip
      - name: Execute glualint
        run: ./glualint .
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare for upload
        run: |
          rm -r .git
          rm -r .github
          rm *.md
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: auto_body_npc
          path: .
