name: LOC Counter

on: [push]

jobs:
  count-loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install SLOC
        run: sudo npm install -g sloc
      - name: Run SLOC
        run: |
          sloc --keys source --details ./ 2>&1 | tee source_loc.txt # For each file.
      - name: Upload lines of code as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: source_loc
          path: source_loc.txt
